### PR TITLE
Add OnePlus X device

### PR DESCRIPTION
**Pull request by ittat**

### CODE REVIEW

**Comment by ittat** [comment]
@lissyx
Hi, Do we need to fork onyx's source tree? 
https://github.com/b2gOS/manifests/pull/3/files#diff-5653a4188e4b028cd82ae1d40a3e3a51R24-R26

**Comment by lissyx** [comment]
> @lissyx
> Hi, Do we need to fork onyx's source tree?
> https://github.com/b2gOS/manifests/pull/3/files#diff-5653a4188e4b028cd82ae1d40a3e3a51R24-R26

Well, you have been able to setup a branch there, so I don't think you need to fork it?

**Review by lissyx — APPROVED** [review]
Same, can you try and rebase so we only have one commit ?

**Comment by ittat** [comment]
> Well, you have been able to setup a branch there, so I don't think you need to fork it?
All right!

**Comment by ittat** [comment]
> > @lissyx
> > Hi, Do we need to fork onyx's source tree?
> > https://github.com/b2gOS/manifests/pull/3/files#diff-5653a4188e4b028cd82ae1d40a3e3a51R24-R26
> 
> Well, you have been able to setup a branch there, so I don't think you need to fork it?


All right

**Comment by ittat** [comment]
> Same, can you try and rebase so we only have one commit ?

Should I close this PR first

**Comment by lissyx** [comment]
> > Same, can you try and rebase so we only have one commit ?
> 
> Should I close this PR first

No, just force-push on each PR

**Comment by lissyx** [comment]
@ittat And ping me on both when it's ready to review / merge :)

**Pull request merged**
